services:
  db:
    image: postgis/postgis:17-3.5-alpine
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    # volumes:
      # - ./data/db:/var/lib/postgresql/data
    ports:
      - "5434:5432"
  redis:
    image: redis:7.4.1-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    env_file:
      - .env
    command: /bin/sh -c 'redis-server --appendonly yes --requirepass $${REDIS_PASSWORD}'
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}